#DUBBO
dubbox:
  application:
    name: xbin-store-web-order
    organization: dubbox
    owner: binux
  registry:
    protocol: zookeeper
    address: 192.168.125.128:2181
  annotation:
    package: cn.binux.controller

#spring:
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
#  freemarker:
#    cache: false
#    request-context-attribute: request

server:
  port: 8107

# swagger2
swagger2.package: cn.binux.controller

# Redis
redisKey:
  # 订单项缓存时间 默认20分钟
  expire_time: 1200
  prefix:
    # Redis购物车商品信息前缀
    cart_order_info_profix: 'CART_ORDER_INFO:'
    # Redis购物车索引信息前缀
    cart_order_index_profix: 'CART_ORDER_INDEX:'

# Cookie 用户登录保存的key
cookie:
  token_login: JKxk8waMTk4PZC
  cookie_cart_key: COOKIE_CART_KEY


#SSO 系统登录页面
sso_login_page: http://localhost:8104/login.html
