#DUBBO
dubbox:
  application:
    name: xbin-store-web-cart
    organization: dubbox
    owner: binux
  registry:
    protocol: zookeeper
    address: 192.168.125.128:2181
  annotation:
    package: cn.binux.controller

#配置模板想到classpath路径，后面须加上"/"
beetl:
  templates-path: templates/
  config:
      html-tag-flag: true
#配置模板的后缀，自动读取spring.mvc.view.suffix
spring:
  mvc:
    view:
      suffix: .html

server:
  port: 8107


# swagger2
swagger2.package: cn.binux.controller

# Cookie Cart key
cookie_cart_key: COOKIE_CART_KEY