#DUBBO
dubbox:
  application:
    name: xbin-store-web-portal
    organization: dubbox
    owner: binux
  registry:
    protocol: zookeeper
    address: 192.168.125.128:2181
  annotation:
    package: cn.binux.controller

#spring:
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
#  freemarker:
#    cache: false
#    request-context-attribute: request

server:
  port: 8101


# swagger2
swagger2.package: cn.binux.controller

# 广告Cid
big_ad_index: 1


